server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zwbzwb123/springcloud-config.git
          username: zwbzwb123
          password: zwb5945945940
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/